spring.application.name=aws-mysql
server.port=8080


# =========================================================
# MySQL Database
# =========================================================
spring.config.import=aws-secretsmanager:myapp/prod/db-pass
aws.region=ap-south-1
spring.datasource.password=${password}
spring.datasource.url=jdbc:mysql://database-1.cfm0oimkyw34.ap-south-1.rds.amazonaws.com:3306/sampledb?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=admin
#spring.datasource.password=Rajasthan#&35


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# Hikari Connection Pool
# =========================================================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# Actuator
# =========================================================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

